### ISSUE TITLE
Success/ failure alerts overlapping

### ISSUE THREAD

**Issue by SidJain1412** [1akshat/json-similarity#1]
In case multiple alerts are shown, they are overlapping over each other, I think this can be fixed by adding `alert-dismissible` to the alert divs in [this file](https://github.com/1akshat/json-similarity/blob/eb18c2e69ae9ea0958691afbac4dbb744030653b/app/views/home/index.html.erb)

Nice tool 👌

**Comment by 1akshat** [comment]
Thanks Sidi. for your review. Its still evolving. I have fixed that now.

**Comment by 1akshat** [comment]
Change UI. Open Modal instead of success alert.
